spring.application.name=chess-web

# Virtual threads
spring.threads.virtual.enabled=true

# Active profiles
spring.profiles.active=dev

# Database config
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Env vars
jwt.issuer=${APP_URL:http://localhost:8080}

# Frontend url
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

server.port=${PORT:8080}