spring.application.name=chess-web

# Virtual threads
spring.threads.virtual.enabled=true

spring.profiles.active=dev

# Database config
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate config
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect